# Generated by Django 5.0.8 on 2026-04-10 18:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import speech.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('repetition', 'Repetition Practice'), ('picture_naming', 'Picture Naming'), ('questions', 'Question & Answer'), ('story_retell', 'Story Retell'), ('category_naming', 'Category Naming')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('prompt_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('text_image', 'Text + Image')], default='text', max_length=20)),
                ('prompt_payload', models.JSONField(blank=True, default=dict, help_text='{"text": "...", "image_url": "...", "audio_url": "..."}')),
                ('expected_text', models.CharField(blank=True, default='', help_text='Expected response text for scoring', max_length=500)),
                ('language', models.CharField(default='en', max_length=10)),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_json', models.JSONField(blank=True, default=dict, help_text='Custom difficulty params per level')),
                ('prompt_levels', models.JSONField(blank=True, default=list, help_text='[{"level": 0, "instruction": "Full model"}, {"level": 3, "instruction": "Independent"}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_speech_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Speech Activities',
                'ordering': ['category', 'difficulty_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpeechRecording',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=speech.models.speech_audio_upload_path)),
                ('consent_snapshot', models.JSONField(blank=True, default=dict, help_text='{"store_audio": false, "retention_days": 0}')),
                ('raw_deleted', models.BooleanField(default=False, help_text='True if raw audio was purged after analysis')),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_recording', to='therapy.sessiontrial')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speech_recordings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_json', models.JSONField(blank=True, default=dict, help_text='Segments with timestamps')),
                ('vad_json', models.JSONField(blank=True, default=dict, help_text='{"segments": [...], "speech_time_ms": ..., "pause_count": ..., "pause_total_ms": ...}')),
                ('features_json', models.JSONField(blank=True, default=dict, help_text='{"duration_ms": ..., "speech_rate_wpm": ..., "energy_mean": ..., ...}')),
                ('target_score_json', models.JSONField(blank=True, default=dict, help_text='{"keyword_match": 0.8, "text_similarity": 0.7, "missing_keywords": [...]}')),
                ('feedback_json', models.JSONField(blank=True, default=dict, help_text='{"suggestions": [...], "severity": "info"}')),
                ('model_versions', models.JSONField(blank=True, default=dict, help_text='{"asr": "whisper-base", "vad": "silero-v4"}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_analyses', to='therapy.sessiontrial')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='speech.speechrecording')),
            ],
            options={
                'verbose_name_plural': 'Speech Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeechTrialMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_text', models.CharField(blank=True, default='', max_length=500)),
                ('target_phoneme', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('prompt_level', models.IntegerField(default=0, help_text='0=Full model, 1=Partial, 2=Gesture, 3=Independent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('attempt_number', models.IntegerField(default=1)),
                ('latency_ms', models.IntegerField(blank=True, help_text='Time from prompt to first speech', null=True)),
                ('therapist_transcript', models.CharField(blank=True, default='', max_length=500)),
                ('therapist_score', models.CharField(blank=True, default='', help_text='success/fail/partial', max_length=20)),
                ('therapist_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_metas', to='speech.speechactivity')),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_meta', to='therapy.sessiontrial')),
            ],
        ),
        migrations.CreateModel(
            name='ASRJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(default='http', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('result_text', models.TextField(blank=True, default='')),
                ('result_confidence', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asr_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asr_jobs', to='therapy.sessiontrial')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='speech_asrj_status_2bd4a4_idx'), models.Index(fields=['trial', 'created_at'], name='speech_asrj_trial_i_7a7d66_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['category'], name='speech_spee_categor_fbbc94_idx'),
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['language'], name='speech_spee_languag_dd1d37_idx'),
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['difficulty_level'], name='speech_spee_difficu_08e98f_idx'),
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['is_active'], name='speech_spee_is_acti_7c6c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='speechrecording',
            index=models.Index(fields=['uploaded_at'], name='speech_spee_uploade_bc89f7_idx'),
        ),
        migrations.AddIndex(
            model_name='speechrecording',
            index=models.Index(fields=['trial'], name='speech_spee_trial_i_832786_idx'),
        ),
        migrations.AddIndex(
            model_name='speechanalysis',
            index=models.Index(fields=['trial', 'created_at'], name='speech_spee_trial_i_c218eb_idx'),
        ),
        migrations.AddIndex(
            model_name='speechanalysis',
            index=models.Index(fields=['processing_status'], name='speech_spee_process_3772f4_idx'),
        ),
        migrations.AddIndex(
            model_name='speechtrialmeta',
            index=models.Index(fields=['category', 'language'], name='speech_spee_categor_725a45_idx'),
        ),
        migrations.AddIndex(
            model_name='speechtrialmeta',
            index=models.Index(fields=['difficulty'], name='speech_spee_difficu_36c2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='speechtrialmeta',
            index=models.Index(fields=['activity'], name='speech_spee_activit_a3515e_idx'),
        ),
    ]
